apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spin-ingress
  namespace: spinnaker
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
  labels:
    app: spin
    cluster: spin-ingress
spec:
  tls:
  - hosts:
    - spinnaker.stackarea.com
    - spinnaker-api.stackarea.com
    secretName: spin-tls-secret
  rules:
  - host: spinnaker.stackarea.com 
    http:
      paths:
      - backend:
          serviceName: spin-deck
          servicePort: 9000
        path: /
  - host: spinnaker-api.stackarea.com 
    http:
      paths:
      - backend:
          serviceName: spin-gate
          servicePort: 8084
        path: /
